# Generated by Django 3.2.13 on 2024-05-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_verified_email',
            new_name='is_verified_email',
        ),
    ]
